version: '3.9'
services:
  mysql:
    image: 'mysql:8'
    environment:
      MYSQL_USER: example
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
    cap_add: [SYS_NICE]
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
volumes:
  mysql-data:
